image: docker:latest

services:
  - docker:dind

######################################## STAGES ########################################

stages:
  - build-and-push
  - deploy

######################################## VARIABLES ########################################

variables:
  IMAGE_NAME: "aishshelke/backend"
  IMAGE_TAG: "$(date +%Y%m%d%H%M%S)-$CI_COMMIT_SHORT_SHA"

######################################## STAGE:BUILD ########################################

build:api:
  image: docker:20.10.9
  services:
    - docker:20.10.9-dind
  stage: build-and-push
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  only:
    - main  

######################################## STAGE:DEPLOY ########################################

deploy:
  image: docker:20.10.9
  services:
    - docker:20.10.9-dind
  stage: deploy
  script:
    - apk add --no-cache kubectl
    - sed -i "s|image: aishshelke/backend:.*|image: aishshelke/backend:$IMAGE_TAG|g" k8s/deployment.yaml
    - kubectl apply -f k8s/
  only:
    - main
