image: docker:latest

services:
  - docker:dind

######################################## STAGES ########################################

stages:
  - build-and-push
  - deploy

######################################## VARIABLES ########################################

variables:
  IMAGE_NAME: "aishshelke/backend"

######################################## STAGE:BUILD ########################################

build:api:
  image: docker:20.10.9
  services:
    - docker:20.10.9-dind
  stage: build-and-push
  script:
    - IMAGE_TAG="$(date +%Y%m%d%H%M%S)-${CI_COMMIT_SHORT_SHA}"
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}
    - docker push ${IMAGE_NAME}:latest
    - echo "IMAGE_TAG=${IMAGE_TAG}" >> build.env
  artifacts:
    reports:
      dotenv: build.env
  only:
    - main  # Adjust this branch as needed

######################################## STAGE:DEPLOY ########################################

deploy:
  image: alpine/k8s:1.21.13
  services:
    - docker:20.10.9-dind
  stage: deploy
  script:
    - apk add --no-cache kubectl
    - source build.env
    - sed -i 's@image@'$TAG'@' k8s/deployment.yaml
    - kubectl apply -f k8s/
  only:
    - main  # Adjust this branch as needed
