image: docker:latest

services:
- docker:dind


######################################## STAGES ########################################

stages:

- build-and-push
- deploy





######################################## STAGE:BUILD ########################################

build:api:
  image: docker:20.10.9
  services:
    - docker:20.10.9-dind
  stage: build-and-push
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t aishshelke/backend:latest .
    - docker push aishshelke/backend:latest




deploy:
  image: docker:20.10.9
  services:
    - docker:20.10.9-dind
  stage: deploy
  script:
    - apk add --no-cache kubectl
    - kubectl apply -f k8s/




