apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: akeso-app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000       # External port
      targetPort: 3000  # Container port
  type: NodePort       # Change to LoadBalancer if using cloud